export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGIN_FALIURE = 'LOGIN_FALIURE'

export const GET_CODE_SUCCESS = 'GET_CODE_SUCCESS'

export const GET_CODE_FALIURE = 'GET_CODE_FALIURE'

export const GET_UNIT_SUCCESS = 'GET_UNIT_SUCCESS'

export const GET_UNIT_FALIURE = 'GET_UNIT_FALIURE'

export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'

export const ADD_CATEGORY_FALIURE = 'ADD_CATEGORY_FALIURE'

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'

export const ADD_PRODUCT_FALIURE = 'ADD_PRODUCT_FALIURE'

export const ADD_SELLER_SUCCESS = 'ADD_SELLER_SUCCESS'

export const ADD_SELLER_FALIURE = 'ADD_SELLER_FALIURE'

export const ADD_SUB_CATEGORY_SUCCESS = 'ADD_SUB_CATEGORY_SUCCESS'

export const ADD_SUB_CATEGORY_FALIURE = 'ADD_SUB_CATEGORY_FALIURE'

export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS'

export const GET_CATEGORY_FALIURE = 'GET_CATEGORY_FALIURE'

export const GET_SELLER_SUCCESS = 'GET_SELLER_SUCCESS'

export const GET_SELLER_FALIURE = 'GET_SELLER_FALIURE'

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS'

export const GET_PRODUCT_FALIURE = 'GET_PRODUCT_FALIURE'

export const GET_PRODUCT_BY_ID_SUCCESS = 'GET_PRODUCT_BY_ID_SUCCESS'

export const GET_PRODUCT_BY_ID_FALIURE = 'GET_PRODUCT_BY_ID_FALIURE'

export const GET_SELLER_BY_ID_SUCCESS = 'GET_SELLER_BY_ID_SUCCESS'

export const GET_SELLER_BY_ID_FALIURE = 'GET_SELLER_BY_ID_FALIURE'

export const GET_SUB_CATEGORY_SUCCESS = 'GET_SUB_CATEGORY_SUCCESS'

export const GET_SUB_CATEGORY_FALIURE = 'GET_SUB_CATEGORY_FALIURE'

export const GET_CATEGORY_LIST_SUCCESS = 'GET_CATEGORY_LIST_SUCCESS'

export const GET_CATEGORY_LIST_FALIURE = 'GET_CATEGORY_LIST_FALIURE'

export const GET_SUB_CATEGORY_LIST_SUCCESS = 'GET_SUB_CATEGORY_LIST_SUCCESS'

export const GET_SUB_CATEGORY_LIST_FALIURE = 'GET_SUB_CATEGORY_LIST_FALIURE'

export const GET_MENUFACTURER_LIST_SUCCESS = 'GET_MENUFACTURER_LIST_SUCCESS'

export const GET_MENUFACTURER_LIST_FALIURE = 'GET_MENUFACTURER_LIST_FALIURE'

export const ADD_MENUFACTURER_LIST_SUCCESS = 'ADD_MENUFACTURER_LIST_SUCCESS'

export const ADD_MENUFACTURER_LIST_FALIURE = 'ADD_MENUFACTURER_LIST_FALIURE'

export const DELETE_MENUFACTURER_LIST_SUCCESS = 'DELETE_MENUFACTURER_LIST_SUCCESS'

export const DELETE_MENUFACTURER_LIST_FALIURE = 'DELETE_MENUFACTURER_LIST_FALIURE'
